from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
)

from reportlab.lib.units import inch


def generate_ats_report(result, output_path):

    styles = getSampleStyleSheet()

    doc = SimpleDocTemplate(output_path)

    story = []

    title = Paragraph(
        "<b><font size=20>ATS Resume Analysis Report</font></b>",
        styles["Title"]
    )

    story.append(title)

    story.append(Spacer(1, 0.3 * inch))

    score = result["ats_score"]

    story.append(
        Paragraph(
            f"<b>Overall ATS Score:</b> {score}/100",
            styles["Heading2"]
        )
    )

    story.append(Spacer(1, 0.2 * inch))

    summary = result["ats_summary"]

    data = [

        ["Resume Length", summary["resume_length"]],

        ["Detected Skills", summary["total_detected"]],

        ["Missing Skills", summary["total_missing"]],

    ]

    table = Table(data, colWidths=[220, 120])

    table.setStyle(

        TableStyle([

            ("BACKGROUND", (0, 0), (-1, 0), colors.lightblue),

            ("GRID", (0, 0), (-1, -1), 1, colors.grey),

            ("BOTTOMPADDING", (0, 0), (-1, -1), 8),

            ("TOPPADDING", (0, 0), (-1, -1), 8),

            ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),

        ])

    )

    story.append(table)

    story.append(Spacer(1, 0.3 * inch))

    story.append(
        Paragraph(
            "<b>Category Breakdown</b>",
            styles["Heading2"]
        )
    )

    for category, score in result["breakdown"].items():

        story.append(
            Paragraph(
                f"{category}: {score}%",
                styles["BodyText"]
            )
        )

    story.append(Spacer(1, 0.2 * inch))

    story.append(
        Paragraph(
            "<b>Detected Skills</b>",
            styles["Heading2"]
        )
    )

    story.append(
        Paragraph(
            ", ".join(result["detected_skills"]),
            styles["BodyText"]
        )
    )

    story.append(Spacer(1, 0.2 * inch))

    story.append(
        Paragraph(
            "<b>Missing Skills</b>",
            styles["Heading2"]
        )
    )

    story.append(
        Paragraph(
            ", ".join(result["missing_skills"]),
            styles["BodyText"]
        )
    )

    review = result["ai_review"]

    for heading, key in [

        ("Strengths", "strengths"),

        ("Weaknesses", "weaknesses"),

        ("Suggestions", "suggestions"),

        ("Career Recommendations", "career_recommendations"),

    ]:

        story.append(Spacer(1, 0.2 * inch))

        story.append(
            Paragraph(
                f"<b>{heading}</b>",
                styles["Heading2"]
            )
        )

        for item in review.get(key, []):

            story.append(
                Paragraph(
                    f"• {item}",
                    styles["BodyText"]
                )
            )

    story.append(Spacer(1, 0.4 * inch))

    story.append(
        Paragraph(
            "<i>Generated by AI Interview Assistant</i>",
            styles["Italic"]
        )
    )

    doc.build(story)